
# Increase file size limit
[server]
maxUploadSize = 1000
port = 5000 #Default is 8501
headless = true

#Change port and set address
[browser]
serverAddress = "team3.bioapp721023.biosci.gatech.edu"
serverPort = 5000

# Set theme
[theme]

primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"
