
# Increase file size limit
[server]
maxUploadSize = 1000


# Set theme
[theme]

primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"